### ISSUE TITLE
if it will support react16.2.0?

### ISSUE THREAD

**Issue by zxydaisy** [ajainarayanan/react-dag#13]
react in our project need to upgrade to 16.2.0,

**Comment by ajainarayanan** [comment]
Hi @zxydaisy As far as I can see it doesn't use any unstable API of react 15.x. So it should work just fine. One thing I would do is add a wrapper around `react-dag` to handle js errors/exceptions in case if any occur. That should not unmount the whole app. Otherwise it should work.


PS: I am working on re-writing the entire project in `Typescript`. It would be useful if you could share the way you are using the component. Would help understand more common usecase.

**Comment by ajainarayanan** [comment]
Closing this as there is not much activity in this thread.
